version: "3"
services:
    nginx:
        container_name: "app_nginx"
        image: nginx
        restart: always
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
        ports:
            - 127.0.0.1:${DOCKER_NGINX_PORT}:80
        depends_on:
            - php
            - mysql
        networks:
            - app_network
    php:
        container_name: "app_php"
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        expose:
            - 9000
        volumes:
            - ./:/var/www
            - ./docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - app_network
    mysql:
        container_name: "app_mysql"
        image: mysql
        restart: always
        volumes:
            - dbdata:/var/lib/mysql
        ports:
            - ${DOCKER_MYSQL_PORT}:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        networks:
            - app_network
    redis:
        container_name: "app_redis"
        image: redis
        restart: always
        expose:
            - 6379
        networks:
            - app_network
networks:
    app_network:
        driver: bridge
volumes:
    dbdata:
        driver: local